# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Poetry Action
      uses: snok/install-poetry@v1.1.8
      with:
        virtualenvs-in-project: true
    - name: Install dependencies
      run:
        make install
    - name: Lint with flake8
      run: 
        make lint
    - name: Test with pytest
      run: 
        make test
  coverage:
      name: coverage
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Poetry Action
        uses: snok/install-poetry@v1.1.8
        with:
          virtualenvs-in-project: true
      - name: Install dependencies
        run:
          make install
      - name: Run tests
        run: |
          make coverage
          
      - uses: paambaati/codeclimate-action@v2.5.3
        if: always()
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE }}

        with:
          coverageCommand: make coverage_xml
